sudo: True

language: python
python:
    - "3.5"

install:
    # - "apt-get install software-properties-common"
    - "sudo add-apt-repository ppa:neovim-ppa/unstable -y"
    - "sudo apt-get update -y"
    - "sudo apt-get install neovim -y"
    - "pip install neovim"
    - "pip install coveralls"
    - "pip install coverage"

# For Testing with gui
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd pytknvim

script:
    - coverage run --source=tests -m py.test -k "not failing"

after_success:
    - coveralls

notifications:
    - email: false
